apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-springbootapp-pvcdata
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 2Gi
  # Uncomment and set your storage class if needed
  # storageClassName: <your-storage-class-name>
